# 工作流的构建任务通常包括：

# actions/checkout：从仓库拉取你的 Jekyll 源代码。

# ruby/setup-ruby：安装你指定的 Ruby 版本。

# 执行 bundle install：安装 Gemfile 中定义的所有插件（包括非白名单插件）。

# 执行 jekyll build：自由地构建你的网站，生成完整的 ./_site 文件夹。

name: Build and Deploy Jekyll Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "/blog"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
